analyzer:
  errors:
    invalid_return_type_for_catch_error: ignore
    library_private_types_in_public_api: ignore
    unused_field: ignore
    use_build_context_synchronously: ignore
# include: package:flutter_lints/flutter.yaml
