# Use uma imagem base com Java e SDK do Android
FROM openjdk:8-jdk

# Instale dependências necessárias
RUN apt-get update && apt-get install -y \
    wget \
    unzip \
    lib32stdc++6 \
    lib32z1

# Baixe e instale o SDK do Android
RUN wget https://dl.google.com/android/repository/sdk-tools-linux-4333796.zip -O sdk-tools-linux.zip \
    && mkdir -p /usr/local/android-sdk \
    && unzip sdk-tools-linux.zip -d /usr/local/android-sdk \
    && rm sdk-tools-linux.zip

# Defina variáveis de ambiente
ENV ANDROID_HOME /usr/local/android-sdk
ENV PATH $ANDROID_HOME/tools:$ANDROID_HOME/tools/bin:$ANDROID_HOME/platform-tools:$PATH

# Aceite as licenças do SDK do Android
RUN yes | sdkmanager --licenses

# Instale as ferramentas e plataformas necessárias
RUN sdkmanager "platform-tools" "platforms;android-29" "build-tools;29.0.3"

# Copie o código da aplicação para o contêiner
WORKDIR /app
COPY . .

# Comando para construir o APK
CMD ["./gradlew", "assembleDebug"]