name: Flutter

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Setup Flutter SDK with a specific version that includes Dart SDK >= 3.4.3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.8' # Substitua pela versão que inclui Dart 3.4.3 ou superior

      # Cache dependencies
      - name: Cache Pub
        uses: actions/cache@v3
        with:
          path: ~/.pub-cache
          key: ${{ runner.os }}-flutter-${{ hashFiles('**/pubspec.yaml') }}

      # Install dependencies
      - name: Install dependencies
        run: flutter pub get

      # Verify formatting
      # - name: Verify formatting
      #   run: flutter format --set-exit-if-changed .

      # Analyze project source
      - name: Analyze project source
        run: flutter analyze

      # Run tests
      - name: Run tests
        run: flutter test
